config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  namespace :host do
    resources :listings
  end
  
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id            :bigint           not null, primary key
#  hosts_id      :bigint           not null
#  title         :string           not null
#  about         :text
#  max_guests    :integer          default(1)
#  address_line1 :string
#  address_line2 :string
#  city          :string
#  state         :string
#  postal_code   :string
#  country       :string
#  lat           :decimal(10, 6)
#  lng           :decimal(10, 6)
#  status        :integer          default(0)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Listing < ApplicationRecord
    validates :title, presence: true
    validates :max_guests, numericality: { greater_than: 0, less_than_or_equal_to: 100 }
    belongs_to :host, class_name: 'User'
    enum status: [:draft, :published, :archived]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  trackable              :datetime
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer
#  unlock_token           :string
#  locked_at              :datetime
#  provider               :string
#  uid                    :string
#  name                   :string
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#
class User < ApplicationRecord
    # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable, :omniauthable
  
  has_many :listings, foreign_key: :host_id

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    user.name = auth.info.name   # assuming the user model has a name
    #user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    user.skip_confirmation!

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/host/listings_controller.rb
class Host::ListingsController < ApplicationController
  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_create_params)
    if @listing.save
      redirect_to host_listings_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :new
    end
  end

  def edit
    @listing = current_user.listings.find(params[:id])
  end

  def update
    @listing = current_user.listings.find(params[:id])
    if @listing.update(listing_update_params)
      redirect_to host_listings_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :edit
    end
  end

  def index
    @listings = current_user.listings.all
  end

  def show
    @listing = current_user.listings.find(params[:id])
  end

  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.update(status: :archived)
    redirect_to host_listings_path
  end

  private

  def listing_create_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests,
      :address_line1,
      :address_line2,
      :city,
      :state,
      :postal_code,
      :country,
    )
  end

  def listing_update_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests
    )
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
    def google
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      else
        session["devise.google_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/host/listings_helper.rb
module Host::ListingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/host/listings/edit.html.erb
<h1>Host::Listings#edit</h1>
<p>Find me in app/views/host/listings/edit.html.erb</p>

app/views/host/listings/index.html.erb
<h1>Your listings</h1>

<% @listings.each do |l| %>
    <%= link_to l.title , host_listing_path(l) %>
<% end %>

app/views/host/listings/new.html.erb
<h1>List your property</h1>

<form action="/host/listings" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="title">Title <br>
        <input type="text" name="listing[title]" id="title" value="<%= @listing.title %>">
    </label>

    <label for="about">About </label>
    <textarea id="about" name="listing[about]"><%= @listing.about %></textarea>

    <label for="max_guests">How many people maxium can stay? </label>
    <input type="number" name="listing[title]" id="max_guests" value="<%= @listing.max_guests %>" min="1" max="100" step="1">

    <input type="submit" value="Create listing">
</form>

app/views/host/listings/show.html.erb
<h1>Host::Listings#show</h1>
<p>Find me in app/views/host/listings/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homeharbor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= button_to "Log out", destroy_user_session_path, method: :delete %>
    <% end %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>


<h1>Home 12321</h1>
<%= link_to 'Sign in', new_user_session_path %>